version: "3.8"
services:
    web:
        container_name: web_container
        build: .
        # command:
            # "python3 manage.py makemigrations --no-input && python3 manage.py migrate --no-input && python3 manage.py runserver 0.0.0.0:8000"
            
            # - "python3 manage.py makemigrations --no-input "
            # "&& python3 manage.py migrate --no-input ython3 manage.py runserver 0.0.0.0:8000"
            # - python3 ./manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        container_name: mysql_container
        restart: always
        # command: '--default-authentication-plugin=mysql_native_password'
        image: mysql:latest
        environment: 
            MYSQL_DATABASE: 'Games'
            # MYSQL_HOST: '127.0.0.1'
            MYSQL_USER: 'sshos'
            MYSQL_PASSWORD: '123'
            MYSQL_ROOT_PASSWORD: '123'
            # MYSQL_PORT: '3306'
        ports: 
            - '31306:3306'
        volumes:
            - games_db:/var/lib/mysql
        expose:
            - '3306'
    
volumes:
    games_db:
